name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print Hollaa
        run: echo "Hooooolllaaa"
      - name: Print Chaooo
        run: echo "Chaaoooooooo"
